import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

export default () => {
  // const [isLogedIn, setIsLogedIn] = useState(false);
  const [userList, setuserList] = useState([]);
  const router = useRouter();
  const getAllUsers = async () => {
    const response = await fetch("/api/allUsers", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        authorization: localStorage.getItem("token") || "",
      },
    });
    const data = await response.json();
    if (data.length > 0) {
      setuserList(data);
    }
    console.log(data);
  };
  useEffect(() => {
    if (localStorage.getItem("token")) {
      // setIsLogedIn(true);
      if (userList.length === 0) {
        getAllUsers();
      }
    } else {
      router.push("/login");
    }
  });

  const addNewUser = async (event:any) => {
    event.preventDefault();
    const response = await fetch("/api/adduser", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        authorization: localStorage.getItem("token") || "",
      },
      body: JSON.stringify({
        firstName: event.target.firstName.value,
        secondName: event.target.secondName.value,
        email: event.target.email.value,
        password: event.target.password.value,
      }),
    });
    const data = await response.json();
    console.log(data);
  };

  return (
    <div>
      <Head>
        <title>fuck you ass hole</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/login">
        <a>Log out</a>
      </Link>
      <main>
        <h1>Welcome to Next.js</h1>
        <form onSubmit={addNewUser}>
          <div>
            <label>First Name:</label>
            <input type="text" name="firstName" />
          </div>

          <div>
            <label>Last Name:</label>
            <input type="text" name="secondName" />
          </div>

          <div>
            <label>Email:</label>
            <input type="text" name="email" />
          </div>

          <div>
            <label>Password:</label>
            <input type="text" name="password" />
          </div>
          <button type="submit">Submit</button>
        </form>

        <div>
          {userList.map((user:User) => {
            return (
              <div key={user.id + "a"} className="card text-center">
                <div key={user.id} className="eachUser card-body center">
                  <p>firstName {user.firstName}</p>
                  <p>secondName {user.secondName}</p>
                  <p>email {user.email}</p>
                  <p>password {user.password}</p>
                </div>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
};

type User = {
  id: number;
  firstName: string;
  secondName: string;
  email: string;
  password: string;
}